-- Add metadata fields to albums table
ALTER TABLE albums ADD COLUMN IF NOT EXISTS label VARCHAR;
ALTER TABLE albums ADD COLUMN IF NOT EXISTS format VARCHAR;
ALTER TABLE albums ADD COLUMN IF NOT EXISTS country VARCHAR;
ALTER TABLE albums ADD COLUMN IF NOT EXISTS genre VARCHAR;
ALTER TABLE albums ADD COLUMN IF NOT EXISTS style VARCHAR;
